name: Deploy to Vercel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
        
    - name: Get Preview URL
      id: preview-url
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "preview-url=https://${{ github.event.pull_request.number }}-pallyflo-nextjs.vercel.app" >> $GITHUB_OUTPUT
        else
          echo "preview-url=https://pallyflo-nextjs.vercel.app" >> $GITHUB_OUTPUT
        fi
        
    - name: Comment Preview URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Preview Deployment Ready!**
            
            **Preview URL:** ${{ steps.preview-url.outputs.preview-url }}
            
            **Deployment Details:**
            - Branch: \`${{ github.head_ref }}\`
            - Commit: \`${{ github.sha }}\`
            - Author: ${{ github.actor }}
            
            **Build Status:** ✅ Success
            **Build Time:** ${{ job.steps[3].conclusion }}
            
            ---
            *This preview will be automatically updated when you push new commits to this branch.*`
          })
          
    - name: Update Deployment Status
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🎉 **Production Deployment Complete!**"
        echo "**Live URL:** https://pallyflo-nextjs.vercel.app"
        echo "**Status:** ✅ Deployed Successfully"
        echo "**Environment:** Production"
